### ISSUE TITLE
Please update docker image to Rust 1.34

### ISSUE THREAD

**Issue by bonzini** [rust-vmm/rust-vmm-ci#1]
For rust-vmm/vm-memory#19 I would like to use optionally the integer atomic types from Rust 1.34.  Right now I would have to keep them out of CI (and not use `--all-features` in the pipeline files), it would be great if you could update the Rust image that buildkite pulls.

**Comment by andreeaflorescu** [comment]
I'll do it today as we also want clippy on aarch64 and it is only available starting with 1.34.

@bonzini for that you will also need to switch from fandree/rust-vmm-dev to rustvmm/dev:v2 once I publish the new version.

**Comment by bonzini** [comment]
Great, please close when rustvmm/dev:v2 is ready.

**Comment by andreeaflorescu** [comment]
@bonzini v2 is now published.
