### ISSUE TITLE
Add possibility to ignore specific advisories in audit test

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/rust-vmm-ci#114]
We've recently hit an issue where an advisory was issued for an unmaintained crate (`atty` - advisory [here](https://rustsec.org/advisories/RUSTSEC-2021-0145)) that several rust-vmm crates depend on. Since there's no apparent way to fix the issue (unresponsive maintainer), we need to allow for certain advisories such as this one to be skipped in the `cargo audit` test. Otherwise, CI will fail and block.

**Comment by andreeaflorescu** [comment]
This can also be disabled at the repository level by adding a file with the name `audit.toml` in `.config/`. An example is available here: https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example.

**Comment by andreeaflorescu** [comment]
We are enabling them per repo instead. Closing this issue.
