### ISSUE TITLE
Integration tests path is not excluded from coverage report

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#22]
When computing the coverage percentage, we should exclude the `tests` directory which included the Rust integration tests.

As a workaround, we can use the `exclude_path` field in the `coverage_config_x86_64.json` and `coverage_config_aarch64.json` and add "tests" to it.

A permanent solution is to add "tests" to the exlude_pattern: https://github.com/rust-vmm/rust-vmm-ci/blob/7e3f307bf0280bc58bf6be09bdbee8ae3375b076/integration_tests/test_coverage.py#L54

**Comment by aghecenco** [comment]
This can (should?) be fixed per crate using the `exclude_path` parameter in `coverage_config.json`. Closing.
