### ISSUE TITLE
Build infrastructure for running performance tests on rust-vmm crates

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/rust-vmm-ci#24]
Add a dedicated Buildkite pipeline for performance tests for each crate that has such tests (alongside the "standard" CI pipeline). In the future, this can help separate performance runs from build / CI runs, and split tests on different machines according to our needs.

It's worth looking into [`critcmp`](https://github.com/BurntSushi/critcmp) as it seems [easy to run](https://medium.com/@yamafaktory/rust-benchmarking-with-criterion-on-travis-ci-%EF%B8%8F-8b54d321e05) and get a verdict from.

Long term, long duration performance tests will demand separate runs (nightly / on some other schedule). To begin with, we can add performance tests in the CI because:
* it's easier to add them there short term
* it will give us early indicators of how long they take
* it will help us assess the stability of results

**Comment by aghecenco** [comment]
See https://github.com/rust-vmm/rust-vmm-container/issue/27 for additions to the `rust-vmm-container`

**Comment by aghecenco** [comment]
See https://github.com/rust-vmm/rust-vmm-ci/issues/24 for additions to `rust-vmm-ci`

**Comment by andreeaflorescu** [comment]
Let's keep this issue open until we add the performance pipeline to the `rust-vmm-ci` instead of having it duplicated in all repositories that require performance tests.

**Comment by aghecenco** [comment]
`test_benchmark.py` is part of `rust-vmm-ci` now. Closing.
