### ISSUE TITLE
Add support for workpace tests

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#38]
For example the coverage test will not work on workspaces because we are using the `--features` flag which is invalid in workspaces and only allowed for packages.

**Comment by lauralt** [comment]
Also, as @aghecenco suspected, we have to add `--all` here: https://github.com/rust-vmm/rust-vmm-ci/blob/master/.buildkite/pipeline.yml#L70 to enable tests for `vmm-reference` workspace. This way, these [lines](https://github.com/rust-vmm/vmm-reference/pull/11/files#diff-80398c5faae3c069e4e6aa2ed11b28c0R13-R21) won't be needed anymore and the issues mentioned [here](https://github.com/rust-vmm/vmm-reference/pull/11#discussion_r486927662) and [here](https://github.com/rust-vmm/vmm-reference/pull/11#discussion_r486953491) about cargo build/run will no longer exist.

**Comment by andreeaflorescu** [comment]
Just noticed that `--all` is deprecated when used on `cargo test`. We should use `--workspace` instead.
