### ISSUE TITLE
Add exception for dependabot on commit format

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#61]
The commit format of depandabot does not confirm to the 50/72 rule of commits. Since this is not in our control, we should add an exception for it.

Log example: https://buildkite.com/rust-vmm/linux-loader-ci/builds/277#7213c428-ba53-4604-a230-7d997e274c3a

**Comment by alexandruag** [comment]
Hmm, does anyone know if there's a way to customize the commit messages generated by dependabot?

**Comment by andreeaflorescu** [comment]
It looks like there is a commit message setting, but it is very limited: https://dependabot.com/docs/config-file/#commit_message and it would not help with all the checks that we have.

Do you have any concerns with having an exception for the dependabot-preview user?

**Comment by alexandruag** [comment]
No, was just curious if there's an easy way to reconcile it with the commit message test.
