### ISSUE TITLE
Provide a way to configure the buildkite pipeline

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#69]
The rust-vmm-ci provides the common tests to be run by all rust-vmm crates. The problem is that we have a few things that should be configurable.

One example is the possibility to configure the devices passed when running the unit tests. For example, vhost tests need access to the vdpa device, but adding it explicitly in the rust-vmm-ci excessively constrains the CI of all other components when this is not in fact needed (i.e. all other components need to run on a host that has access to the vdpa device, and the vdpa device needs to be passed to the docker image when running the tests). More details about this here: https://github.com/rust-vmm/rust-vmm-ci/issues/64

**Comment by andreeaflorescu** [comment]
An initial proposal here: #70. The dynamic pipeline allows specifying things like:
- what agent to run on (in case we want to add specialized agents)
- the docker cofiguration (to be able to specify devices).

This is tested with kvm-ioctls by running the pipeline as follows:
```DOCKER_PLUGIN_CONFIG="devices: [ "/dev/kvm" ]" ./rust-vmm-ci/.buildkite/generate_pipeline.py | buildkite-agent pipeline upload```

**Comment by lauralt** [comment]
Fixed by #76
