### ISSUE TITLE
`clippy` is not run on `mod tests`

### ISSUE THREAD

**Issue by acatangiu** [rust-vmm/rust-vmm-ci#7]
How about we add `--profile test` to `clippy`:
```bash
cargo clippy --all --profile test -- -D warnings
```

**Comment by andreeaflorescu** [comment]
When we first discussed adding clippy to the rust-vmm-ci we decided against testing the test profile. In tests we often do things that clippy doesn't approve on purpose.

If you think there's value in adding the test profile as well, we can discuss it again in the following rust-vmm meeting. Should we add it to the meeting agenda?

**Comment by acatangiu** [comment]
Not really. I haven't yet seen any tests doing weird/dangerous things that `clippy` would protect against, so for now I don't have any strong data-points for or against.

Closing this for now and will reopen if needed.
