### ISSUE TITLE
Update test_commit_format.py to work locally

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#71]
This test is taking a dependency on Buildkite specific infrastructure. Specifically, it expect the following environment variables to be set in order to run the test: `BUILDKITE_PULL_REQUEST_BASE_BRANCH` and `BUILDKITE_REPO`.

We need to find good defaults for those environment variables in case they're not set so that we can run the tests locally. The challenge here comes from identifying a good default for the `BUILDKITE_PULL_REQUEST_BASE_BRANCH` as this is the branch we use for figuring out which commits are part of the PR.

From a short round of thinking, I could not find a perfect solution. A meh solution would be to always assume that the base branch is the `master` of the configured `origin` remote. This is a meh solution because it implies that the developer updates their local master branch from the upstream master branch so that the diff in commits is truly what is on the local branch from which they wish to open a PR. This assumes good practices (for example PRs are never opened from the master branch).

Other solutions are welcomed.

**Comment by lauralt** [comment]
Fixed by #72
