### ISSUE TITLE
Deprecate static Buildkite pipeline

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#77]
To be able to eventually delete the static pipeline from rust-vmm-ci we need to update the CI for the existing components to use the autogenerate script instead (as specified in the [readme](https://github.com/rust-vmm/rust-vmm-ci#getting-started-with-rust-vmm-ci)).

This issue tracks the progress per component:

- [x] vm-fdt
- [x] vhost-device
- [x] kvm-bindings
- [ ] crate-template (N/A)
- [ ] io-rate-limiter (N/A)
- [x] mshv
- [x] seccompiler
- [x] vhost-user-backend
- [x] vfio-ioctls
- [x] vm-memory
- [x] vm-virtio
- [x] vm-device
- [x] linux-loader
- [x] vhost
- [x] event-manager
- [x] vm-superio
- [x] vmm-sys-util
- [x] virtio-bindings
- [x] kvm-ioctls
- [x] vmm-reference
- [x] vfio-bindings
- [ ] vm-allocator (N/A)

**Comment by andreeaflorescu** [comment]
Mini runbook for deprecating the static pipeline:
1. Merge dependabot PR that updates rust-vmm-ci in each corresponding repository.
2. Update Buildkite steps and run: `./rust-vmm-ci/.buildkite/autogenerate_pipeline.py | buildkite-agent pipeline upload` instead of the static `buildkite-agent pipeline upload ./rust-vmm-ci/.buildkite/pipeline.yml`.
3. Make sure that the tests are running by triggering a build in Buildkite on the main/master branch & wait for it to finish
4. If the build is green, mark the crate as upgraded in the issue here

**Comment by lauralt** [comment]
All rust-vmm repositories are using now the autogenerated pipeline. The CI is failing in vhost because there's no vhost-vdpa-0 device on the arm instance, but it shouldn't be related to the pipeline switch. We are investigating this issue separately.
