### ISSUE TITLE
Add test for cargo audit

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/rust-vmm-ci#8]
We shouldn't have too many crates that we depend on, but still it is worth checking cargo audit as part of our CI.

Detail here: https://github.com/RustSec/cargo-audit

**Comment by anth1y** [comment]
@andreeaflorescu I'd like to be assigned to this issue.. but i think i need to be added to the org ?

**Comment by andreeaflorescu** [comment]
Hey @anth1y, I've assign you. I also thought that you need to be part of an org to be assigned to an issue, but it seems that has changed.

Let me know if you need help with anything :)
